server:
  port: 8761

spring:
  application:
    name: discoveryservice

# registry? service ????? ?? (default: true)
# eureka server? ?? ??? client? ??
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
#    서비스를 종료해도 레지스트리에 남아있는 경우 적용
    # service? ???? server registry? ???? ?? ?? ??.
#    개발 시점에만 사용하고 운영 시에는 삭제해야 하는 속성
    # heart beat? ???? ??? ??? ?????? ??.
#    거짓으로 설정하면 하트비트가 들어오지 않으면 제거
    # ??? ??? ????, ?? ???? ???? ?? prop.
    enable-self-preservation: false
#    클라이언트로부터 하트비트가 수신되는지 점검 (기본: 60초)
    eviction-interval-timer-in-ms: 3000
